sudo: required
services:
  - docker
language: python

matrix:
  include:
    - python: '3.5'
      env: TOX_ENV=app_tests_cov_upload
    - python: '3.5'
      env: TOX_ENV=app_flake8
    - python: '3.5'
      env: TOX_ENV=tests_flake8
    - python: '3.4'
      env: TOX_ENV=app_tests
    - python: '3.3'
      env: TOX_ENV=app_tests
    - python: '3.2'
      env: TOX_ENV=app_tests
    - python: '3.5'
      env: TOX_ENV=app_todo
    - python: '3.5'
      env: TOX_ENV=tests_todo

addons:
  apt:
    packages:
      - libffi6
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
