language: python
python:
  - '3.5'
  - '3.4'
  - '2.7'
env:
  - TOX_ENV=tests_flake8
  #- TOX_ENV=tests_todo
  - TOX_ENV=app_tests
  - TOX_ENV=app_flake8
  #- TOX_ENV=app_todo
addons:
  apt:
    packages:
      - libffi6
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
