language: python
python:
  - '3.5'
  - '3.4'
  - '2.7'
env:
  - TOX_ENV=standard
  #- TOX_ENV=standard_noop #TODO
  - TOX_ENV=flake8
addons:
  apt:
    packages:
      - libffi6
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
