sudo: required
language: python

matrix:
  include:
    - python: '3.4'
      env:
        - TOX_ENV=app_tests_min
        - START_INTEGRATION_SERVERS=yes
      services:
        - docker

    - python: '3.5'
      env:
        - TOX_ENV=app_tests_cov_upload
        - START_INTEGRATION_SERVERS=yes
      services:
        - docker
    - python: '3.5'
      env:
        - TOX_ENV=app_flake8
    - python: '3.5'
      env:
        - TOX_ENV=tests_flake8

    - python: '3.6'
      env:
        - TOX_ENV=app_tests_min
        - START_INTEGRATION_SERVERS=yes
    - python: '3.6'
      env:
        - TOX_ENV=app_flake8
    - python: '3.6'
      env:
        - TOX_ENV=tests_flake8

    - python: '3.7'
      env:
        - TOX_ENV=app_tests_min
        - START_INTEGRATION_SERVERS=yes
    - python: '3.7'
      env:
        - TOX_ENV=app_flake8
    - python: '3.7'
      env:
        - TOX_ENV=tests_flake8

addons:
  apt:
    packages:
      - libffi6
install:
  - pip install tox
script:
  - |
    test "${START_INTEGRATION_SERVERS}" = 'yes' && docker run -d -p 10143:143 -p 10993:993 -p 6379:6379 -v /dev/random:/dev/random:ro --name tabellarius_tests bechtoldt/tabellarius_tests-docker
    tox -e ${TOX_ENV}
