type: object
properties:
  accounts:
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-z0-9_-]+$":
        type: object
        additionalProperties: false
        properties:
          enabled:
            type: boolean
          server:
            type: string
          port:
            type: integer
          username:
            type: string
          password:
            type: string
          sort_mailbox:
            type: string
          pre_inbox:
            type: string
          pre_inbox_search:
            type: string
          password_enc:
            type: string
          imaps:
            type: boolean
          starttls:
            type: boolean
          tlsverify:
            type: boolean
  filters:
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-z0-9_-]+$":
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-z0-9_-]+$":
            type: object
            additionalProperties: false
            properties:
              commands:
                type: array
                items:
                  "$ref": "#/definitions/command"
              rules:
                type: array
                items:
                  "$ref": "#/definitions/rule"
  settings:
    type: object
    additionalProperties: false
    properties:
      logging:
        type: object
      gpg_use_agent:
        type: boolean
definitions:
  command:
    type: object
    additionalProperties: false
    properties:
      type:
        type: string
        pattern: "^(move)$"
      target:
        type: string
      add_flags:
        type: array
        items:
          type: string
          enum:
            - '\Answered'
            - '\Deleted'
            - '\Draft'
            - '\Flagged'
            - '\Recent'
            - '\Seen'
  rule:
    type: object
    additionalProperties: false
    patternProperties:
      "^(or|and)$":
        type: array
        items:
          - type: object
            additionalProperties: false
            patternProperties:
              "^[A-Za-z0-9_-]+$":
                type: array
                additionalItems: false
                items:
                  type: string
